sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-precise
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=create-centos-6
  - INSTANCE=create-centos-7
  - INSTANCE=create-debian-8
  - INSTANCE=create-ubuntu-1404
  - INSTANCE=create-ubuntu-1604
  - INSTANCE=create-fedora-25
  - INSTANCE=create-opensuse-leap
  - INSTANCE=create-swappiness-centos-6
  - INSTANCE=create-swappiness-centos-7
  - INSTANCE=create-swappiness-debian-8
  - INSTANCE=create-swappiness-ubuntu-1404
  - INSTANCE=create-swappiness-ubuntu-1604
  - INSTANCE=create-swappiness-fedora-25
  - INSTANCE=create-swappiness-opensuse-leap

# Ensure we make ChefDK's Ruby the default
before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

matrix:
  include:
    script:
      - /opt/chefdk/embedded/bin/chef --version
      - /opt/chefdk/embedded/bin/cookstyle --version
      - /opt/chefdk/embedded/bin/foodcritic --version
      - /opt/chefdk/bin/chef exec rake
    env: UNIT_AND_LINT=1
